### ISSUE TITLE
Does not identify snippets via 'render' tag

### ISSUE THREAD

**Issue by rickydazla** [packdigital/liquid-snippet-import-detection#1]
Since the [include tag has been deprecated](https://shopify.dev/docs/themes/liquid/reference/tags/deprecated-tags#include), it would be great if this extension could support the [render tag](https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags#render)

**Comment by tshamz** [comment]
whoops, a little late here but better late than never amirite?
